### PR TITLE
Move _containerLeft init before transform

### PR DESCRIPTION
**Pull request by fnicollet**
Fixes issue in https://github.com/hyperknot/Leaflet/issues/3 that was reproduced with https://github.com/hyperknot/Leaflet/issues/3#issuecomment-229182323

### CODE REVIEW

**Comment by hyperknot** [comment]
Great, we just need to fix the `zoomAnimation: false` case, as that one is skipped now.

**Comment by fnicollet** [comment]
True! But I just tried leaflet master and zoomAnimation is broken, even with the most basic example. Probably a regression after the recent changes. Will log an issue in leaflet

**Comment by fnicollet** [comment]
Bah it didn't work in RC1 either, I guess this option is not really enabled that much ahah

**Comment by hyperknot** [comment]
You mean zoomAnimation: false is broken? I cannot see it. Can you describe it? Also I'm on gitter.

**Pull request merged**
